name: Code Coverage Demo

on:
  push:
    branches:
main
  pull_request:
    branches:
main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project CodeCoverage.xcodeproj -scheme CodeCoverage -destination 'platform=iOS Simulator,name=iPhone Pro Max,OS=15.2' build test
