name: Code Coverage demo
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 13.2.1
        run: sudo xcode-select -switch /Applications/Xcode.app
#      - name: Testing iOS app
#        run: exec ./.github/scripts/test_app.sh
#      - name: Run tests with Coverage
#        run: swift test --enable-code-coverage
      - name: Test coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
